# NOTE: update this with your service name
service: serverless-nodejs-starter

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  - serverless-dotenv-plugin 

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
